# Generated by Django 4.1.7 on 2023-04-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
