# Generated by Django 3.2.10 on 2023-05-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlesearchconsoletokendata',
            old_name='scope',
            new_name='scopes',
        ),
    ]
