# Generated by Django 3.2.10 on 2023-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_searchanalytics_searchconsoleresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchConsoleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('clicks', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('impressions', models.IntegerField()),
                ('position', models.FloatField()),
            ],
        ),
    ]
