# Generated by Django 3.2.10 on 2023-05-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_scope_googlesearchconsoletokendata_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesearchconsoletokendata',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlesearchconsoletokendata',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
