# Generated by Django 3.2.10 on 2023-05-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSearchConsoleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
    ]
