# Generated by Django 3.2.10 on 2023-05-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_googlesearchconsoletokendata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlesearchconsoletokendata',
            old_name='access_token',
            new_name='token',
        ),
    ]
